### ISSUE TITLE
Is T5 also learned during Prompt Tuning?

### ISSUE THREAD

**Issue by jeewoo1025** [thunlp/Prompt-Transferability#14]
Hello, Thank you for the good work.

Is T5 also learned during Prompt Tuning?
When I check the learnable layers, I found that not only the prompt but also the T5 model is learned.
I am confused about **whether PLM is frozen or not during training** because I believe the previous prompt tuning (https://arxiv.org/abs/2104.08691) is that PLM is frozen and only the soft prompt is unfrozen.

**▶ Command**
```
gpus=0
BACKBONE=T5
DATASET=SST2

CUDA_VISIBLE_DEVICES=$gpus python3 train.py --config config/${DATASET}Prompt${BACKBONE}.config --gpu $gpus
```

**▶ Add Code lines**
I add below codes on line 159 `Prompt-Transferability-1.0/tools/train_tool.py` ([link](https://github.com/thunlp/Prompt-Transferability/blob/main/Prompt-Transferability-1.0/tools/train_tool.py))
```
    # Check encoder-decoder requires_grad T/F
    for name, param in model.named_parameters():
        print(name, param.requires_grad)
```

**▶ Results**

![230726](https://github.com/thunlp/Prompt-Transferability/assets/39071676/1f119ac5-75dc-49fa-8c21-eefd7b2fa6f3)

Sincerely,
Jeewoo Sul

**Comment by yushengsu-thu** [comment]
Hello Jeewoo,
In line 197, you can find the `model.zero_grad()`. So, the parameters of will not be optimized. 
<img width="792" alt="Screen Shot 2023-07-31 at 12 14 23 PM" src="https://github.com/thunlp/Prompt-Transferability/assets/11704492/df96c4d9-ffee-4f98-9506-3a4f3faf0c28">
You can also try to directly re-used the provided T5's prompts on the corresponding tasks on the T5 backbone. I believe these prompts can work (if I train the T5's parameters, these prompts should not work on T5).

Besides, I recommend that you can use Prompt_transferability-2.0. We re-factor the original experimental code and make it more readable.

Thanks

**Comment by jeewoo1025** [comment]
Thank you for your kind answr.

**Comment by yushengsu-thu** [comment]
@jeewoo1025 

No problem. Feel free to mail me if you have any further question :D
