### ISSUE TITLE
question about paper

### ISSUE THREAD

**Issue by TwjLoveCode** [thunlp/Prompt-Transferability#4]
文中的跨任务cross task是不是也可以叫做跨域cross domain了呢？比如SA情感分类中，movie到restaurant的zero-shot transfer，他们属于同一种任务SA，但是他们的distribution不一样，所以也可是说是cross domain了。若理解有误，见谅

**Comment by yushengsu-thu** [comment]
Yes. From the perspective of experimental results, we can get the conclusions you said.
