### ISSUE TITLE
Report bugs in "Prompt-Transferability-2.0-latest/prompt_hub/hub.py "

### ISSUE THREAD

**Issue by Ultramarine-spec** [thunlp/Prompt-Transferability#9]
- line 244
```model, template, verbalizer, plm, tokenizer, model_config, tokenizer_wrapper_class, model_type = self.get_model(args.backbone, processor, args)```
**args** should be changed to **self.args**
```model, template, verbalizer, plm, tokenizer, model_config, tokenizer_wrapper_class, model_type = self.get_model(self.args.backbone, processor, self.args)```
- The code seems to be only suitable for models like **Roberta** that use **mask** to predict labels. For models like **t5**, I think change **PromptForClassification**  into **PromptForGeneration** on line 100 might work.

**Comment by CyraxSector** [comment]
> * line 244
>   `model, template, verbalizer, plm, tokenizer, model_config, tokenizer_wrapper_class, model_type = self.get_model(args.backbone, processor, args)`
>   **args** should be changed to **self.args**
>   `model, template, verbalizer, plm, tokenizer, model_config, tokenizer_wrapper_class, model_type = self.get_model(self.args.backbone, processor, self.args)`
> * The code seems to be only suitable for models like **Roberta** that use **mask** to predict labels. For models like **t5**, I think change **PromptForClassification**  into **PromptForGeneration** on line 100 might work.

Hi, have you successfully setup Prompt-Transferability-2.0 in your local PC? If so, could you please guide me on major steps. Thanks in advance!

**Comment by yushengsu-thu** [comment]
@Ultramarine-spec  Hello, you can check the latest version of Prompt-Transferability-2.0-latest. It already solved this problem.
